### ISSUE TITLE
CI: fix rust caching

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/runtimes#134]
Eg [here](https://github.com/polkadot-fellows/runtimes/actions/runs/7409368464/job/20159489326?pr=132) it prints `No cache found` although there should be some?!  
Also seems to happen on other branches. Maybe @alvicsam knows how to fix it? Can we maybe even use this new Parity caching tool?

The `check-migrations` job could also need some caching for its build 😅

**Comment by bkchr** [comment]
Will be fixed by: https://github.com/polkadot-fellows/runtimes/pull/135

**Comment by ggwpez** [comment]
I still dont get whats going on.  

In [this](https://github.com/polkadot-fellows/runtimes/actions/runs/7461967014/job/20303211183) job, it restored fine from key `v0-rust-fellowship-cache-35cfef99`, now in [another job](https://github.com/polkadot-fellows/runtimes/actions/runs/7462837903/job/20306115920) it fails to restore from the same key.  
The second job even ran after the first one 🤔

**Comment by bkchr** [comment]
Hmm weird :see_no_evil:

**Comment by alvicsam** [comment]
I removed `shared-key` in this PR https://github.com/polkadot-fellows/runtimes/pull/142 and now it runs faster because each workflow has its own cache. Usually the first run in a PR doesn't use cache (it might download it from the `main` branch but cargo will not use it). But then the cache action will upload the updated version and use it in the next runs. Also GitHub cache is only [10GB for repo](https://github.com/polkadot-fellows/runtimes/actions/caches) and now one PR uses ~3GB of it. The good news is that GitHub doesn't erase the oldest cache immediately so it can be used for some time.

> In [this](https://github.com/polkadot-fellows/runtimes/actions/runs/7461967014/job/20303211183#step:8:67) job, it restored fine from key v0-rust-fellowship-cache-35cfef99, now in [this one](https://github.com/polkadot-fellows/runtimes/actions/runs/7462837903/job/20306115920#step:8:66) it fails to restore from the same key. The second job even ran after the first one 🤔

In this case [enabling debug for runners](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) can help to understand what went wrong.

**Comment by bkchr** [comment]
Wait, what? But what @ggwpez was for downloading the cache? Then we should really move to only generate the cache in the `main` branch and only download them in prs. I added the `shared-key` exactly to not always rebuild everything the first time a pr is opened.

**Comment by alvicsam** [comment]
In this case each workflow (clippy, migrations and tests) should have unique `shared-key`.

**Comment by bkchr** [comment]
Ahh each job! Ty!

**Comment by ggwpez** [comment]
CI seems to work now and picks up cache across branches, thanks.
