### ISSUE TITLE
Review bot error: Reviews may only be requested from collaborators

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/runtimes#405]
CI from [here](https://github.com/polkadot-fellows/runtimes/actions/runs/10111050996/job/27962220434?pr=381):  

```pre
gh: Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the polkadot-fellows/runtimes repository. (HTTP 422)
{"message":"Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the polkadot-fellows/runtimes repository.","documentation_url":"https://docs.github.com/rest/pulls/review-requests#request-reviewers-for-a-pull-request","status":"422"}
Error: Process completed with exit code 1.
```

cc @Bullrich

**Comment by seadanda** [comment]
Looks like this is related to the migration to the People Chain - identities are off the relay and now the bot thinks that nobody is a collaborator (there are no Github handles where it's looking). I haven't looked into the bot code yet but if you look at the logs for the "Get github handle of the fellows stage" it doesn't even connect to Polkadot People.

Also compare that stage of the action to the [most recent PR merged to main](https://github.com/polkadot-fellows/runtimes/pull/398/checks) and you can see that it doesn't find the github handles, but the stage is still passing. It then fails later because nobody who has reviewed it is a collaborator.

**Comment by seadanda** [comment]
Looks like it is now fixed: https://github.com/paritytech/review-bot/pull/131

Pending release and confirmation that this is the same cause

**Comment by ggwpez** [comment]
Yea waiting for approvals here now: https://github.com/polkadot-fellows/runtimes/pull/409

**Comment by seadanda** [comment]
Yea the same error would be triggered if somebody outside the fellowship (or not listed as a collaborator) reviewed the PR before it was changed.
Seems like getting the list of collaborators from the GitHub API and then using it to filter the list of reviewers before re-requesting a review would sort it.

**Comment by ggwpez** [comment]
Fixed not it seems.
